# Generated by Django 5.0.3 on 2024-03-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0003_alter_profile_is_looking_for_collaborator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
